#------------------------------------------------#
# SPACEBOOK CONFIGURATION Official Launch Handbook
#------------------------------------------------#
#
#        |
#       / \
#      / _ \        See spacebook.app for
#     |.o '.|       more documentation!
#     |'._.'|
#     |     |
#   ,'|  |  |`.
#  /  |  |  |  \
#  |,-'--|--'-.| 
#
#------------------------------------------------
# GENERAL SETTINGS
# name
#   * the main title or header for your spacebook
# shortName
#   * a short version of your name, for smaller screens
#   * optional
# subtitle
#   * the short subtitle that appears below your site name
#   * optional
# shortSubtitle
#   * a short version of your subtitle, for smaller screens
#   * optional
# description 
#   * used to populate your site metadata
#   * shows up in search results and in social sharing
# url
#   * The main URL to your site (use full URL)
#------------------------------------------------
name = "Spacebook v1.0"
shortName = "Spacebook Inc"
subtitle = "Create a modern notebook to document or explain almost anything."
shortSubtitle = "Create a modern notebook today."
description = "Create a modern notebook to document or explain almost anything."
url =  "https://spacebook.app"

#------------------------------------------------
# GIT SETTINGS
# gitUrl
#   * The full URL to your git repository
# gitBranch
#   * Your primary git branch
#------------------------------------------------
gitUrl = "https://github.com/broeker/spacebook-demo"
gitBranch = "main"

#------------------------------------------------
# FAVICON
# enableFaviconEmoji
#   * Use any emoji for your favicon
# faviconEmoji
#   * If true, paste your favorite emoji here
#
# Note: You can leave this set to false to use the
# default favicon, or add your own custom favicon
# to the includes/assets/ folder!
#------------------------------------------------
enableFaviconEmoji = false 
faviconEmoji = "ðŸ’¥"

#------------------------------------------------
# SITE FEATURES
# enableDarkmode
#   * Set to true to enable darkmode toggle
# enableSearch
#   * Set to true to enable Elastic Lunr search
# enableEditButton
#   * Set to true to enable an "edit this page" link
# enableDatestamp
#   * Set to true to enable a datestamp
# enablePageNavigation
#   * Set to true to enable page-by-page navigation
# enableEncryption
#   * Set to true to enable logout button
#   * See https://spacebook.app/advanced/encryption/
# enableContact
#   * Set to true to enable a Netlify contact form icon
# enableComments
#   * Set to true to enable a commenting engine
#   * See https://spacebook.app/advanced/comments/
#------------------------------------------------
enableDarkmode = true
enableSearch = true
enableEditButton = true
enableDatestamp = true
enablePageNavigation = true
enableEncryption = true
enableContact = true
enableComments = true

#------------------------------------------------
# PLACEHOLDER AND DEFAULT TEXT
# searchPlaceholder
#   * Change text for search bar placeholder
# searchNoResultsMessage
#   * Change message for no search results

#------------------------------------------------
searchPlaceholder = "Search "
searchNoResultsMessage = "Sorry cadet, no results available!"

#------------------------------------------------
# NAVIGATION STYLE
# Set your navigation style to vertical (left-hand
# sidebar), horizontal (top), or both (dynamic toggle)
# navigationStyle
#   * toggle (let the user toggle between sidebar/top)
#   * horizontal (sidebar-only)
#   * vertical (top-only)
#------------------------------------------------
navigationStyle = "toggle"


#------------------------------------------------
# FOOTER
#------------------------------------------------
# footerText (appears at the center of your bottom footer)
# To use raw HTML in your use a multiline tomls string, e.g.:
# 
# footerText = """
# <div><strong>Acme Inc and the California Office of Design</strong></div>
# <div>Where all the news is fit to print</div>
# <ul>
#    <li>Foo: 612-555-5555</li>
#    <li>Address: Yorba, CA 55410-0000</li>
#    <li>Website: <a href="http://spacebook.app" target="_blank">spacebook.app</li>
#</ul>
#------------------------------------------------#



#------------------------------------------------#
# CMS INTEGRATION (Netlify or Forestry)
#------------------------------------------------#
#  enableCMS (show the CMS admin icon in footer)
#------------------------------------------------#
enableCMS = true
#------------------------------------------------#