backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "content/images" # Media files will be stored in the repo under images/uploads

# # Cloudinary
# media_library:
#   name: cloudinary
#   config:
#     cloud_name: broeker
#     api_key: 159818251742281

collections:
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "content/pages"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 100 }
          - { label: "Parent", name: "parent", widget: "string", required: false, hint: "(Optional) Enter a matching parent key to set this a nested or child page" }
          - { label: "Title", name: "title", widget: "string",  required: false, hint: "(Optional) Enter alternate text for navigation link" }
      - { label: "Body", name: "body", widget: "markdown" }


#  - label: "Globals"
#    name: "globals"
#    files:
#      - label: "Site Data"
#        name: "site_data"
#        delete: false
#        file: "_data/config.toml"
#        fields:
#          - {label: "Site name", name: "name", widget: "string"}
#          - {label: "Site subtitle", name: "subtitle", widget: "string", required: false}
#          - {label: "Meta description", name: "description", widget: "string"}
#          - {label: "Site footer", name: "footer", widget: "string", required: false}
#          - {label: "Site Url", name: "url", widget: "string"}
#          - {label: "Github Url", name: "gitUrl", widget: "string"}
#          - {label: "Github branch", name: "gitBranch", widget: "string"}
#          - {label: "Navigation style", name: "navigationStyle", widget: "string"}
#          - {label: "Site emoji", name: "emoji", widget: "string", required: false}
#          - {label: "Enable search", name: "enableSearch", widget: "boolean"}
#          - {label: "Enable darkmode", name: "enableDarkMode", widget: "boolean"}
#          - {label: "Enable edit button", name: "enableEditButton", widget: "boolean"}
#          - {label: "Enable datestamp", name: "enableDatestamp", widget: "boolean"}
#          - {label: "Enable Github link", name: "enableGithubLink", widget: "boolean"}
#          - {label: "Enable contact form", name: "enableContact", widget: "boolean"}
#          - {label: "Enable Netlify CMS", name: "enableNetlifyCMS", widget: "boolean", default: false}
#          - {label: "Enable comments", name: "enableComments", widget: "boolean", default: false}
#          - {label: "Enable encryption", name: "enableEncryption", widget: "boolean", default: false}
#          - {label: "Enable page navigation", name: "enablePageNavigation", widget: "boolean", default: false}